name: inventory_1
version: 1.0.6+6
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  fluttertoast: ^8.0.9
  modal_bottom_sheet: ^3.0.0-pre
  logger: ^1.1.0
  uuid: ^3.0.6
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  rename: ^2.0.1

    

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter: 
  assets: 
    - assets/
  uses-material-design: true

